package com.redis.product.mapper;

import com.redis.product.dto.request.ProductRequest;
import com.redis.product.dto.response.ProductResponse;
import com.redis.product.entity.Product;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.math.BigDecimal;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

@DisplayName("ProductMapper Unit Tests")
class ProductMapperTest {

    private ProductMapper productMapper;

    @BeforeEach
    void setUp() {
        // Pure Unit Test: No Spring boot or Mockito needed
        productMapper = new ProductMapper();
    }

    @Test
    @DisplayName("toEntity() - Should map fields, sanitize name, and round decimals")
    void toEntity_ShouldMapCorrectly() {
        // Arrange
        ProductRequest request = ProductRequest.builder()
                .name("   Sony   PlayStation   5  ") // Multi space and padding
                .price(new BigDecimal("49999.567"))  // Needs 2 decimal rounding
                .rating(new BigDecimal("4.84"))      // Needs 1 decimal rounding
                .stockQuantity(15)
                .build();

        // Act
        Product entity = productMapper.toEntity(request);

        // Assert
        assertThat(entity).isNotNull();
        assertThat(entity.getName()).isEqualTo("Sony PlayStation 5"); // Sanitized
        assertThat(entity.getPrice()).isEqualByComparingTo("49999.57"); // Rounded Half-Up
        assertThat(entity.getRating()).isEqualByComparingTo("4.8"); // Rounded Half-Up
        assertThat(entity.getStockQuantity()).isEqualTo(15);
        assertThat(entity.getId()).isNull(); // ID is generated by database, must be null
    }

    @Test
    @DisplayName("updateEntity() - Should update entity fields and sanitize inputs")
    void updateEntity_ShouldModifyFields() {
        // Arrange
        Product existingProduct = Product.builder()
                .id(1L)
                .name("Old Name")
                .price(new BigDecimal("100.00"))
                .rating(new BigDecimal("3.0"))
                .stockQuantity(5)
                .build();

        ProductRequest request = ProductRequest.builder()
                .name("  New Name  ")
                .price(new BigDecimal("150.755"))
                .rating(new BigDecimal("4.55"))
                .stockQuantity(12)
                .build();

        // Act
        productMapper.updateEntity(existingProduct, request);

        // Assert
        assertThat(existingProduct.getId()).isEqualTo(1L); // Unchanged
        assertThat(existingProduct.getName()).isEqualTo("New Name"); // Sanitized
        assertThat(existingProduct.getPrice()).isEqualByComparingTo("150.76"); // Rounded
        assertThat(existingProduct.getRating()).isEqualByComparingTo("4.6"); // Rounded
        assertThat(existingProduct.getStockQuantity()).isEqualTo(12);
    }

    @Test
    @DisplayName("toResponse() - Should map fields and derive stock status correctly")
    void toResponse_ShouldMapFieldsAndStockStatus() {
        // Arrange (Test Out of Stock)
        Product outOfStockProduct = Product.builder()
                .id(10L)
                .name("Out of Stock Item")
                .price(new BigDecimal("1000.00"))
                .rating(new BigDecimal("4.0"))
                .stockQuantity(0)
                .build();

        // Act
        ProductResponse response = productMapper.toResponse(outOfStockProduct);

        // Assert
        assertThat(response.getId()).isEqualTo(10L);
        assertThat(response.getName()).isEqualTo("Out of Stock Item");
        assertThat(response.getStockQuantity()).isEqualTo(0);
        assertThat(response.getStockStatus()).isEqualTo("OUT_OF_STOCK");
        assertThat(response.getIsAvailable()).isFalse();
        assertThat(response.getPriceFormatted()).contains("1,000.00"); // Checking currency formatting

        // Test Low Stock (stock <= 10)
        Product lowStockProduct = Product.builder()
                .stockQuantity(5)
                .price(new BigDecimal("500.00"))
                .build();
        ProductResponse lowStockResponse = productMapper.toResponse(lowStockProduct);
        assertThat(lowStockResponse.getStockStatus()).isEqualTo("LOW_STOCK");
        assertThat(lowStockResponse.getIsAvailable()).isTrue();

        // Test In Stock (stock > 10)
        Product inStockProduct = Product.builder()
                .stockQuantity(11)
                .price(new BigDecimal("500.00"))
                .build();
        ProductResponse inStockResponse = productMapper.toResponse(inStockProduct);
        assertThat(inStockResponse.getStockStatus()).isEqualTo("IN_STOCK");
        assertThat(inStockResponse.getIsAvailable()).isTrue();
    }

    @Test
    @DisplayName("toResponseList() - Should map multiple entities to responses")
    void toResponseList_ShouldMapAll() {
        // Arrange
        Product p1 = Product.builder().id(1L).name("P1").price(new BigDecimal("10")).stockQuantity(2).build();
        Product p2 = Product.builder().id(2L).name("P2").price(new BigDecimal("20")).stockQuantity(20).build();

        // Act
        List<ProductResponse> responses = productMapper.toResponseList(List.of(p1, p2));

        // Assert
        assertThat(responses).hasSize(2);
        assertThat(responses.get(0).getId()).isEqualTo(1L);
        assertThat(responses.get(1).getId()).isEqualTo(2L);
    }
}
